Refactor clone_pkg() style

diff --git a/check_pkg b/check_pkg
--- a/check_pkg
+++ b/check_pkg
@@ -337,11 +337,17 @@ clone_pkg ()
     local gh=https://github.com/archlinux/aur
     local aur=https://aur@aur.archlinux.org/
 
-    if ! git clone --single-branch --branch "$package" "${gh}".git "$package"; then
-        printf '%s\n' "Failed to clone $package from $gh" >&2
+    if ! git clone \
+        --single-branch \
+        --branch "$package" \
+        "$gh".git \
+        "$package"
+    then
+        local err="Failed to clone $package from"
+        printf '%s\n' "$err $gh" >&2
 
         if ! git clone "${aur}$package".git; then
-            printf '%s\n' "Failed to clone $package from $aur" >&2
+            printf '%s\n' "$err $aur" >&2
             exit 1
         fi
     fi
