Tidy code + add epoch mismatch logic

diff --git a/.github/workflows/aur_bump.yml b/.github/workflows/aur_bump.yml
--- a/.github/workflows/aur_bump.yml
+++ b/.github/workflows/aur_bump.yml
@@ -61,7 +61,7 @@ jobs:
       matrix:
         package: ${{ fromJson(needs.fetch-packages.outputs.packages) }}
 
-      max-parallel: 6
+      max-parallel: 6  # Minimize servers load
 
     steps:
       - name: 'Generate GitHub App token'
@@ -90,10 +90,15 @@ jobs:
 
           set -o pipefail
 
+          repo=${{ github.repository }}
           package=${{ matrix.package }}
           printf '%s\n' "Checking $package version"
 
-          git clone https://aur@aur.archlinux.org/"$package".git
+          if ! git clone https://aur@aur.archlinux.org/"$package".git; then
+              printf '%s\n' "Failed to clone $package from AUR" >&2
+              exit 1
+          fi
+
           cd "$package" || exit 1
 
           config=.nvchecker.toml
@@ -115,6 +120,93 @@ jobs:
           upstream_url=$url
           package_url=https://aur.archlinux.org/packages/$pkgbase
 
+          list_issue()
+          {
+              local type=$1
+              local search=$2
+              local label=$3
+
+              if ! gh issue list \
+                  --repo "$repo" \
+                  --search "author:app/aur-bump-bot '$search' in:title" \
+                  --label "$label" \
+                  --state open \
+                  --limit 1 \
+                  --json number \
+                  --jq '.[].number'
+              then
+                  printf '%s\n' "$pkgbase: failed to check $type issue for $pkgbase" >&2
+                  exit 1
+              fi
+          }
+
+          view_issue()
+          {
+              local type=$1
+              local issue=$2
+
+              if ! gh issue view \
+                  "$issue" \
+                  --repo "$repo" \
+                  --json body \
+                  --jq '.body'
+              then
+                  printf '%s\n' "$pkgbase: failed to fetch $type issue #$issue" >&2
+                  exit 1
+              fi
+          }
+
+          edit_issue()
+          {
+              local type=$1
+              local issue=$2
+              local title=$3
+              local body=$4
+
+              if ! gh issue edit \
+                  "$issue" \
+                  --repo "$repo" \
+                  --title "$title" \
+                  --body "$body"
+              then
+                  printf '%s\n' "$pkgbase: failed to update $type issue #$issue" >&2
+                  exit 1
+              fi
+          }
+
+          create_issue()
+          {
+              local type=$1
+              local label=$2
+              local title=$3
+              local body=$4
+
+              if ! gh issue create \
+                  --repo "$repo" \
+                  --label "$label" \
+                  --title "$title" \
+                  --body "$body"
+              then
+                  printf '%s\n' "$pkgbase: failed to create $type issue" >&2
+                  exit 1
+              fi
+          }
+
+          close_issue()
+          {
+              local type=$1
+              local issue=$2
+
+              if ! gh issue close \
+                  "$issue" \
+                  --repo "$repo" \
+                  --comment "Current version $pkgver is latest, closing the issue."
+              then
+                  printf '%s\n' "$pkgbase: failed to close $type issue #$issue" >&2
+                  exit 1
+              fi
+          }
+
           # Get upstream version using nvchecker.
           if upstream_version=$(
               nvchecker \
@@ -134,100 +226,107 @@ jobs:
                       exit 1
                   fi
 
-                  # Check if issue already exists.
-                  if ! issue=$(
-                      gh issue list \
-                          --repo ${{ github.repository }} \
-                          --search "author:app/aur-bump-bot '$pkgbase - new version: ' in:title" \
-                          --label 'package out-of-date' \
-                          --state open \
-                          --limit 1 \
-                          --json number \
-                          --jq '.[].number'
-                      )
-                  then
-                      printf '%s\n' "$pkgbase: failed to check issue for $pkgbase" >&2
-                      exit 1
-                  fi
+                  # Check if package out-of-date issue exists.
+                  search_ood="$pkgbase - new version: "
+                  label_ood='package out-of-date'
+                  issue_ood=$(list_issue 'out-of-date' "$search_ood" "$label_ood")
+
+                  # Check if epoch mismatch issue exists.
+                  search_epoch="$pkgbase - version mismatch"
+                  label_epoch='package needs-epoch'
+                  issue_epoch=$(list_issue 'epoch' "$search_epoch" "$label_epoch")
 
                   if (( result == 0 )); then
                       printf '%s\n' "$pkgbase: current version $pkgver is latest"
 
-                      if [[ -n $issue ]]; then
-                          printf '%s\n' "$pkgbase: current version $pkgver is latest, closing existing issue #$issue"
+                      if [[ -n $issue_ood ]]; then
+                          printf '%s\n' "$pkgbase: closing existing issue #$issue_ood"
 
-                          if ! gh issue close \
-                              "$issue" \
-                              --repo ${{ github.repository }} \
-                              --comment "Current version $pkgver is latest, closing the issue."
-                          then
-                              printf '%s\n' "$pkgbase: failed to close issue #$issue" >&2
-                              exit 1
-                          fi
+                          close_issue 'out-of-date' "$issue_ood"
                       fi
 
+                      if [[ -n $issue_epoch ]]; then
+                          printf '%s\n' "$pkgbase: closing existing issue #$issue_epoch"
+
+                          close_issue 'epoch' "$issue_epoch"
+                      fi
                   elif (( result < 0 )); then
                       printf '%s\n' "$pkgbase: current version $pkgver is newer than $upstream_version"
+
+                      title_epoch="$pkgbase - version mismatch"
+                      body_epoch="pkgbase: $pkgbase
+          pkgver: $pkgver
+          upstream_version: $upstream_version
+          upstream_url: $upstream_url
+          package_url: $package_url
+
+          > [!NOTE]
+          > The pkgver version is newer than upstream, this means:
+          > - Upstream changed versioning schemes
+          > - nvchecker is pointing to the wrong source
+          > - An \`epoch\` bump is needed
+          >
+          > Since this breaks pacman's version comparison logic, review *.nvchecker.toml* and consider adding/incrementing \`epoch\` in *PKGBUILD*."
+
+                      if [[ -n $issue_epoch ]]; then
+                          # Extract versions from existing epoch issue.
+
+                          existing_body_epoch=$(view_issue 'epoch' "$issue_epoch")
+
+                          mapfile -t body_arr_epoch <<< "$existing_body_epoch"
+
+                          for i in "${body_arr_epoch[@]}"; do
+                              [[ $i = pkgver:* ]]           && existing_pkgver_epoch=${i#*: }
+                              [[ $i = upstream_version:* ]] && existing_upstream_epoch=${i#*: }
+                          done
+
+                          # Only update if versions have changed.
+                          if [[ $existing_pkgver_epoch != "$pkgver" || $existing_upstream_epoch != "$upstream_version" ]]; then
+                              printf '%s\n' "$pkgbase: updating epoch issue #$issue_epoch with new versions"
+
+                              edit_issue 'epoch' "$issue_epoch" "$title_epoch" "$body_epoch"
+                          else
+                              printf '%s\n' "$pkgbase: epoch issue #$issue_epoch already has current version info"
+                          fi
+                      else
+                          printf '%s\n' "$pkgbase: creating epoch issue"
+
+                          create_issue 'epoch' 'package needs-epoch' "$title_epoch" "$body_epoch"
+                      fi
                   elif (( result > 0 )); then
                       printf '%s\n' "$pkgbase: upgrade from version $pkgver to $upstream_version"
 
-                      title="$pkgbase - new version: $upstream_version"
-                      body="pkgbase: $pkgbase
+                      title_ood="$pkgbase - new version: $upstream_version"
+                      body_ood="pkgbase: $pkgbase
           pkgver: $pkgver
           upstream_version: $upstream_version
           upstream_url: $upstream_url
           package_url: $package_url"
 
-                      if [[ -n $issue ]]; then
-                          # Extract versions from existing issue.
+                      if [[ -n $issue_ood ]]; then
+                          # Extract versions from existing out-of-date issue.
 
-                          if ! existing_body=$(
-                              gh issue view \
-                                  "$issue" \
-                                  --repo ${{ github.repository }} \
-                                  --json body \
-                                  --jq '.body'
-                              )
-                          then
-                              printf '%s\n' "$pkgbase: failed to fetch issue #$issue" >&2
-                              exit 1
-                          fi
+                          existing_body_ood=$(view_issue 'out-of-date' "$issue_ood")
 
-                          mapfile -t body_arr <<< "$existing_body"
+                          mapfile -t body_arr_ood <<< "$existing_body_ood"
 
-                          for i in "${body_arr[@]}"; do
-                              [[ $i = pkgver:* ]]           && existing_pkgver=${i#*: }
-                              [[ $i = upstream_version:* ]] && existing_upstream=${i#*: }
+                          for i in "${body_arr_ood[@]}"; do
+                              [[ $i = pkgver:* ]]           && existing_pkgver_ood=${i#*: }
+                              [[ $i = upstream_version:* ]] && existing_upstream_ood=${i#*: }
                           done
 
                           # Only update if versions have changed.
-                          if [[ $existing_pkgver != "$pkgver" || $existing_upstream != "$upstream_version" ]]; then
-                              printf '%s\n' "$pkgbase: updating issue #$issue with new versions"
+                          if [[ $existing_pkgver_ood != "$pkgver" || $existing_upstream_ood != "$upstream_version" ]]; then
+                              printf '%s\n' "$pkgbase: updating out-of-date issue #$issue_ood with new versions"
 
-                              if ! gh issue edit \
-                                  "$issue" \
-                                  --repo ${{ github.repository }} \
-                                  --title "$title" \
-                                  --body "$body"
-                              then
-                                  printf '%s\n' "$pkgbase: failed to update issue #$issue" >&2
-                                  exit 1
-                              fi
+                              edit_issue 'out-of-date' "$issue_ood" "$title_ood" "$body_ood"
                           else
-                              printf '%s\n' "$pkgbase: issue #$issue already has current version info"
+                              printf '%s\n' "$pkgbase: out-of-date issue #$issue_ood already has current version info"
                           fi
                       else
-                          printf '%s\n' "$pkgbase: creating issue"
+                          printf '%s\n' "$pkgbase: creating out-of-date issue"
 
-                          if ! gh issue create \
-                              --repo ${{ github.repository }} \
-                              --label 'package out-of-date' \
-                              --title "$title" \
-                              --body "$body"
-                          then
-                              printf '%s\n' "$pkgbase: failed to create issue #$issue" >&2
-                              exit 1
-                          fi
+                          create_issue 'out-of-date' 'package out-of-date' "$title_ood" "$body_ood"
                       fi
                    fi
               else
